# Plato Input Catalogue (PIC) 2.1.0.1

This notebook explores the PIC 2.1.0.1 catalogue and its sub-PICs. Ultimately the goal of this work is to produce feather-format files that can used by `picsim` to generate on-demand stellar catalogues to be used by `platonium`.

**Prerequsites** 

To run this notebook you need to download the PIC 2.1.0.1 and  place following files alonside this notebook:

- `LOPS2PICtarget2.1.0.1-t-fg-c-scv.fits`
- `LOPS2PICcontaminant2.1.0.1-t-fg-c-scv.fits`

**Documentation** 

The following technical notes helps you understand the PIC:

- `LOPS2PIC2.1.0.1_DataDefinitionDocument_PLATO-SSDC-PDC-DD-0003.pdf`
- `LOPS2PIC2.1.0.1_ReleaseNote_PLATO-SSDC-PDC-DN-0001.pdf`
- `PLATO-DLR-PL-RP-0001_i4.3.pdf`
- `PLATO-DLR-PL-TN-0113_issue1.0_PLATO_instrument_spectral_response.pdf`
- `PLATO-KUL-PMC-TN-0001_i1.0_Science_Calibration_Stars_Input_Catalogue_Requirements_Justification.pdf`
- `PLATO_SCI_UPD_TN_0022_1.2.pdf`

**Last checked** 

This notebook was last functional with the PlatoSim version:

- `PlatoSim 3.7.0-191-g42fc64d4`

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib notebook

In [28]:
# Default packages
import os
import sys
import glob

# PlatoSim default
import scipy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# PLATOnium default
from astropy.table import Table
from pathlib import Path

# PlatoSim libraries
import platosim.utilities as ut
from platosim.matplotlibrc import setup_paper
setup_paper(warning=False)

from IPython.display import display, HTML
display(HTML("<style>.container {width:90% !important; }</style>"))

# Remove when done testing
path = Path(os.getenv('PLATO_PROJECT_HOME')) / 'inputfiles/data_picsim/LOPS2PIC2.1.0.1-t-fg-c-scv/Data'

## LOPS2PICtarget2.1.0.1-t-fg-c-scv

This catalogue is the main target table, composed by the merge of four different target lists:

- `tPIC`: core science stars (P1, P2, P4, P5) and stars with confirmed/candidate planet(s)
- `fgPIC`: Fine Guidance System (FGS) stars used to guarantee the attitude of the spacecraft
- `cPIC`: instrument calibration stars
- `scvPIC`: calibration and validation stars for both stellar and exoplanets science

Load target catalogue into data frame:

In [29]:
table = Table.read(path / 'LOPS2PICtarget2.1.0.1-t-fg-c-scv.fits', format='fits')
df = table.to_pandas()
df.head()

,PICid,PICname,StarName,RAdeg,eRAdeg,DEdeg,eDEdeg,pmRA,epmRA,pmDE,...,tPICplanetFlag,fgPICcPICvariabilityFlag,targetStatusFlag,BOLrandomSysNSRNCAM_T,BOLnCameraObsNCAM_T,BOLnCameraSatNCAM_T,tPICscientificRanking,scvPICscientificRanking,scientificPriority,scheduledTarget
0,3101157000090,b'PIC 3101157000090',b'Gaia DR3 4648912462785101312',77.412564,0.215359,-76.366669,0.203062,21.182822,0.017576,9.356322,...,0,<NA>,0,0.0,0,0,0.013229,<NA>,<NA>,<NA>
1,3101154000089,b'PIC 3101154000089',b'Gaia DR3 4624905073068112128',76.078145,0.180463,-76.358820,0.165314,-19.300017,0.014557,45.793454,...,0,2,0,0.0,0,0,0.008808,<NA>,<NA>,<NA>
2,3101150000139,b'PIC 3101150000139',b'Gaia DR3 4625081785202904576',73.206962,0.148628,-76.339396,0.165777,6.514479,0.012161,80.011497,...,2,<NA>,0,0.0,0,0,1.000000,<NA>,<NA>,<NA>
3,3101160000169,b'PIC 3101160000169',b'Gaia DR3 4648857654708471680',79.291288,0.506761,-76.335616,0.544995,7.474767,0.040898,39.637395,...,0,<NA>,0,0.0,0,0,0.013229,<NA>,<NA>,<NA>
4,3100554000004,b'PIC 3100554000004',b'Gaia DR3 4625093536233494272',75.447761,0.208898,-76.334756,0.156004,2.850393,0.016913,18.483772,...,0,<NA>,0,0.0,0,0,0.002860,<NA>,<NA>,<NA>

Check the column names:

In [30]:
df.columns

Index(['PICid', 'PICname', 'StarName', 'RAdeg', 'eRAdeg', 'DEdeg', 'eDEdeg',
       'pmRA', 'epmRA', 'pmDE', 'epmDE', 'pm', 'epm', 'Plx', 'ePlx',
       'distance', 'edistance', 'Glon', 'Glat', 'posEpoch', 'refEpoch',
       'posPropFlag', 'PlatoMagNCAM', 'ePlatoMagNCAM', 'PlatoMagFCAMb',
       'ePlatoMagFCAMb', 'PlatoMagFCAMr', 'ePlatoMagFCAMr', 'Gmag', 'eGmag',
       'BPmag', 'eBPmag', 'RPmag', 'eRPmag', 'Hpmag', 'eHpmag', 'Ksmag',
       'eKsmag', 'AG', 'eAG', 'AKs', 'eAKs', 'EBPRP', 'eEBPRP', 'extStatus',
       'VmagCalculated', 'eVmagCalculated', 'Teff', 'eTeff', 'Radius',
       'eRadius', 'Mass', 'eMass', 'caseFlag', 'PICmainSourceFlagBOL',
       'tPICsourceFlagNCAM_BOL', 'fgPICsourceFlag', 'cPICsourceFlag',
       'scvPICsourceFlag', 'NSSFlag', 'qualityFlag', 'tPICplanetFlag',
       'fgPICcPICvariabilityFlag', 'targetStatusFlag', 'BOLrandomSysNSRNCAM_T',
       'BOLnCameraObsNCAM_T', 'BOLnCameraSatNCAM_T', 'tPICscientificRanking',
       'scvPICscientificRanking', 'scientificPriority', 'scheduledTarget'],
      dtype='object')

Define a new dataframe and copy over the columns we need:

In [57]:
dt = pd.DataFrame()
dt['PIC'] = df.PICid
dt['gaiaDR3'] = df.StarName
dt['ra'] = df.RAdeg
dt['dec'] = df.DEdeg
dt['pmRA'] = df.pmRA
dt['pmDec'] = df.pmDE
dt['Pmag'] = df.PlatoMagNCAM
dt['PBmag'] = df.PlatoMagFCAMb
dt['PRmag'] = df.PlatoMagFCAMr
dt['Teff'] = df.Teff
dt['R'] = df.Radius
dt['M'] = df.Mass
dt['case'] = df.caseFlag
dt['source'] = df.PICmainSourceFlagBOL
dt['tPIC'] = df.tPICsourceFlagNCAM_BOL
dt['fgPIC'] = df.tPICsourceFlagNCAM_BOL
dt['cPIC'] = df.tPICsourceFlagNCAM_BOL
dt['scvPIC'] = df.tPICsourceFlagNCAM_BOL
dt['ncams'] = df.BOLnCameraObsNCAM_T
# dt[''] = df.

Change bitmask values of source flag defining the sub-PICs:

In [58]:
dt['source'].replace(0, np.nan, inplace=True)
dt['source'].replace(1, 'Prime', inplace=True)
dt['source'].replace(2, 'Proprietary', inplace=True)
dt['source'].replace(4, 'tPIC', inplace=True)
dt['source'].replace(8, 'fgPIC', inplace=True)
dt['source'].replace(16, 'cPIC', inplace=True)
dt['source'].replace(32, 'scvPIC', inplace=True)

Change bitmask values of source flag defining the target-PIC (tPIC):

In [59]:
dt['tPIC'].replace(0, np.nan, inplace=True)
dt['tPIC'].replace(1, 'P1', inplace=True)
dt['tPIC'].replace(2, 'P2', inplace=True)
dt['tPIC'].replace(4, 'P5', inplace=True)
dt['tPIC'].replace(8, 'P4', inplace=True)
dt['tPIC'].replace(16, 'Planet', inplace=True)
dt['tPIC'].replace(32, 'Prime', inplace=True)
dt['tPIC'].replace(64, 'Proprietary', inplace=True)

Change bitmask values of source flag defining the fine-guidance-PIC (fgPIC):

In [60]:
dt['fgPIC'].replace(0, 'normal', inplace=True)
dt['fgPIC'].replace(1, 'blue', inplace=True)
dt['fgPIC'].replace(2, 'red', inplace=True)

Change bitmask values of source flag defining the calibration-PIC (cPIC):

In [ ]:
dt['cPIC'].replace(0, 'Reset', inplace=True)
dt['cPIC'].replace(1, '', inplace=True)
dt['cPIC'].replace(2, '', inplace=True)
dt['cPIC'].replace(4, '', inplace=True)
dt['cPIC'].replace(8, '', inplace=True)
dt['cPIC'].replace(16, '', inplace=True)
dt['cPIC'].replace(32, '', inplace=True)
dt['cPIC'].replace(64, '', inplace=True)
dt['cPIC'].replace(128, '', inplace=True)
dt['cPIC'].replace(256, '', inplace=True)
dt['cPIC'].replace(512, '', inplace=True)

In [61]:
dt

,PIC,gaiaDR3,ra,dec,pmRA,pmDec,Pmag,PBmag,PRmag,Teff,R,M,case,source,tPIC,fgPIC,cPIC,scvPIC,ncams
0,3101157000090,b'Gaia DR3 4648912462785101312',77.412564,-76.366669,21.182822,9.356322,13.657177,14.553798,13.024910,3706.570156,0.528598,0.553083,2,tPIC,P4,8,8,8,0
1,3101154000089,b'Gaia DR3 4624905073068112128',76.078145,-76.358820,-19.300017,45.793454,9.256633,9.434113,9.042751,6336.650983,2.309631,1.513401,1,20,P1,blue,1,1,0
2,3101150000139,b'Gaia DR3 4625081785202904576',73.206962,-76.339396,6.514479,80.011497,12.748182,13.665532,12.108849,3683.410321,0.566664,0.591101,2,tPIC,24.0,24,24,24,0
3,3101160000169,b'Gaia DR3 4648857654708471680',79.291288,-76.335616,7.474767,39.637395,14.662250,15.469214,14.062296,3827.306464,NaN,NaN,2,tPIC,P4,8,8,8,0
4,3100554000004,b'Gaia DR3 4625093536233494272',75.447761,-76.334756,2.850393,18.483772,12.276307,12.563166,11.963726,5444.886474,2.035617,1.236851,1,tPIC,P5,4,4,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309782,2701781001169,b'Gaia DR3 5521878683251408896',129.233279,-45.850102,-3.330392,5.541941,11.866110,11.960058,11.742967,NaN,NaN,NaN,5,scvPIC,NaN,normal,0,0,6
309783,2828738002075,b'Gaia DR3 5311568741986840832',138.766609,-52.956875,-4.389595,5.282324,12.922842,13.049013,12.767500,9256.349000,1.832289,2.091048,3,scvPIC,NaN,normal,0,0,6
309784,2915705000334,b'Gaia DR3 5302678949933344000',131.828040,-58.654483,-5.721946,4.512396,12.625162,12.769855,12.446155,7249.924000,1.633806,1.516936,3,scvPIC,NaN,normal,0,0,6
309785,2938214000635,b'Gaia DR3 5299816611932024320',139.030793,-60.254665,-7.302593,3.677567,11.254923,11.356901,11.123499,7832.615700,2.743980,2.087701,3,scvPIC,NaN,normal,0,0,6
309786,3027369003996,b'Gaia DR3 4660119441251843584',83.028084,-67.589762,1.543843,0.506920,14.388827,14.353806,14.440216,29717.610000,NaN,NaN,5,scvPIC,NaN,normal,0,0,6

In [ ]:
dt[''].replace(, '', inplace=True)

That's it! The output feather-format catalogues are placed on the KU Leuven FTP located at `/STER/platoman/ftp`. Located there `picsim` automatically downloads these files upon first execution and you can enjoy the user-friendly interface of `picsim` to generate your sub-PIC catalogues used by `PlatoSim`.